### ISSUE TITLE
No provider version available for `darwin_arm64`

### ISSUE THREAD

**Issue by skos-ninja** [cyrilgdn/terraform-provider-rabbitmq#18]
Right now the provider has no released binary for `darwin_arm64` and as such you are unable to use this provider on Apple M1 devices. 

Would you be able to release a version of the provider that targets `darwin_arm64` so this provider can be used?

### Terraform Version
`Terraform v1.0.3
on darwin_arm64`

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    rabbitmq = {
      source  = "cyrilgdn/rabbitmq"
      version = "1.5.1"
    }
  }
  required_version = ">= 1.0.0"
}
```

### Panic Output
```
Error: Incompatible provider version

Provider registry.terraform.io/cyrilgdn/rabbitmq v1.5.1 does not have a package available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
```

**Comment by haines** [comment]
v1.6.0 includes a darwin_arm64 binary 🎉

**Comment by cyrilgdn** [comment]
Indeed, sorry I totally forgot to ping you here and close the issue.

**Comment by skos-ninja** [comment]
No worries. Thank you for releasing a compatible version
