### ISSUE TITLE
Shovel resource doesn't update

### ISSUE THREAD

**Issue by mced** [cyrilgdn/terraform-provider-rabbitmq#2]
Hi @cyrilgdn 

### Terraform Version
```bash
Terraform v0.13.5
+ provider registry.terraform.io/cyrilgdn/rabbitmq v1.5.1
```

### Affected Resource(s)
- `rabbitmq_shovel`

### Expected Behavior
Replace the resource

### Actual Behavior
`Error: doesn't support update`

**Comment by zdenek-biberle** [comment]
Just came across this as well. An okay workaround is to make sure that the name of the shovel changes as well, that will force Terraform to recreate it.

I have literally zero knowledge about Terraform plugins, but looking at [this file](https://github.com/cyrilgdn/terraform-provider-rabbitmq/blob/master/rabbitmq/resource_shovel.go), it seems to me that adding `ForceNew: true` to everything would help with this, right?
