### ISSUE TITLE
rabbitmq_user resource fails while applying

### ISSUE THREAD

**Issue by aggarwalaman1191** [cyrilgdn/terraform-provider-rabbitmq#20]
### Terraform Version
1.0.0

### Affected Resource(s)
rabbitmq_user

### Terraform Configuration Files
resource "rabbitmq_user" "cloudamqp_users" {
  name = "test"
  password = "test"
  tags = ["administrator", "management"]
}

### Expected Behavior
Create users successfully in cloudamqp

### Actual Behavior
It creates user in the cloudamqp but terraform apply fails with below error:

**Error: json: cannot unmarshal array into Go struct field UserInfo.tags of type string**
with rabbitmq_user.cloudamqp_users
on test.tf line 50, in resource "rabbitmq_user" "cloudamqp_users":
resource "rabbitmq_user" "cloudamqp_users" {

Can you help what could be the issue here?

**Comment by tgraskemper** [comment]
I can confirm for me it's an issue with 3.9.5 as I am able to create users through TF in 3.7.27 and 3.8.21.  I haven't tested all 3.9.x versions but I'll update if I find out more.

**Comment by crisp2u** [comment]
This looks fixed in the latest version of rabbithole and that version is used on master. @cyrilgdn Can we have a new release with the master code that contains the fix for this ? We are blocked by this and we don't want to fork the provider just for this.

**Comment by hareshdk19** [comment]
@tgraskemper @crisp2u @aggarwalaman1191  Can you please give an approximate date when it can be released ?

**Comment by cyrilgdn** [comment]
@crisp2u @hareshdk19 I'll trigger a release this evening (CEST) or tomorrow.

**Comment by cyrilgdn** [comment]
[v1.6.0](https://registry.terraform.io/providers/cyrilgdn/rabbitmq/latest) has been released today, let me know if it fixes your issue.

**Comment by aggarwalaman1191** [comment]
thanks @cyrilgdn , this worked pretty well. :)

**Comment by Sweatha-g** [comment]
@cyrilgdn I am using rabbit version 3.9.6 and using latest provider v1.6.0 to create resources and it throws error while creating my vhost and user  " Error 405 from RabbitMQ:EOF"

**Comment by berniedurfee-renaissance** [comment]
> @cyrilgdn I am using rabbit version 3.9.6 and using latest provider v1.6.0 to create resources and it throws error while creating my vhost and user " Error 405 from RabbitMQ:EOF"

@Sweatha-g were you able to resolve this issue?

**Comment by Sweatha-g** [comment]
Hi, no we’re not able to and I finally had to create resources manually
without terraform, as I had deadlines.

**Comment by Mrunu07** [comment]
@Sweatha-g 
https://github.com/cyrilgdn/terraform-provider-rabbitmq/issues/29#issuecomment-1806280408
was helpfull we had an additional / in our provider and removing it worked
