### ISSUE TITLE
Feature request: Data sources

### ISSUE THREAD

**Issue by Skeen** [cyrilgdn/terraform-provider-rabbitmq#35]
Hello,

I'm using a single AMQP instance for multitenancy, with each tenant getting their own vhost on the AMQP instance.

Currently configuration of all tenants must reside within a single Terraform configuration, as there are no data resources available ease splitting up the configuration.

The separation I desire is a intertenant Terraform configuration which creates a vhost, a user and permissions tying the two together per tenant, and then a set of tenant specific Terraform configurations which utilize the intertenant created user to further create queues, exchanges, bindings and integration-specific user and corresponding permissions.

The idea being to delegate responsibilities closer to the responsible components, following the separation of concerns design principle.

### Affected Resource(s)
Potentially all resources, but for my use-case mainly `rabbitmq_vhost`.

**Comment by taybin** [comment]
I'd love to see this too.
