### ISSUE TITLE
Terraform registry release

### ISSUE THREAD

**Issue by zerkms** [cyrilgdn/terraform-provider-rabbitmq#39]
Hi team,

could you also please update the version in the terraform registry at https://registry.terraform.io/providers/cyrilgdn/rabbitmq/

Thank you!

**Comment by cyrilgdn** [comment]
Hi @zerkms ,

Thanks for reporting it, it's normally automatic when pushing Github tag but the release failed and I missed that.

It's now correctly released: https://registry.terraform.io/providers/cyrilgdn/rabbitmq/1.7.0
