### ISSUE TITLE
Provider is extremely slow post upgrade to last version of terraform

### ISSUE THREAD

**Issue by william00179** [cyrilgdn/terraform-provider-rabbitmq#42]
Hi there,

I have just upgraded our clusters to K8s 1.23 along with various tools on our deployment infrastructure to their latest versions

OS: Ubuntu focal arm64
K8s: 1.23
AWS CLI: aws-cli/2.7.29 Python/3.9.11 Linux/5.15.0-1019-aws exe/aarch64.ubuntu.20 prompt/off
Terraform: Terraform v1.2.8 on linux arm64
Rabbitmq Provider: 1.7.0

I started to experience extremely slow state refresh on rabbitmq resources. We only have about 20 or so in our state and it is taking in excess of 10 minutes to refresh them. 

I have looked at the trace logs from the provider and I can't see any errors or anything else otherwise wrong.

Similarly on the rabbitmq clusters, there are no errors in the logs, and browsing the management console is performant.

We are experiencing this issue on multiple clusters and different terraform deployments / states.

Refresh of resources from other providers (AWS, Kubernetes) is behaving normally.

**Comment by cyrilgdn** [comment]
@william00179 Hello, what was the issue? (in case someone else encounters the same problem)
