### ISSUE TITLE
Feature request : Operator policy

### ISSUE THREAD

**Issue by MrLuje** [cyrilgdn/terraform-provider-rabbitmq#5]
Hi,

I may have missed it but I didn't find a way to declare an [operator policy](https://www.rabbitmq.com/parameters.html#operator-policies) 
If it's not already available, it would be a nice addition to this provider

Many thanks for this provider :)

**Comment by cyrilgdn** [comment]
Hi @MrLuje ,

It's indeed not possible currently. We'll add this as a feature request,  I'll check if it's easily doable or not.

**Comment by MrLuje** [comment]
Hi @cyrilgdn, would you accept a PR for it ? 
From what I gathered, it should be first implemented in rabbithole library.

**Comment by cyrilgdn** [comment]
@MrLuje Yes of course, feel free to open a PR :blush:

**Comment by wimi** [comment]
I'd love to use that, any plans for release?
