### ISSUE TITLE
Not able to create vhost in cloudampq rabbitmq

### ISSUE THREAD

**Issue by vrathore18** [cyrilgdn/terraform-provider-rabbitmq#7]
I tried to create vhost using this provider but I am not able to. 

```
provider "rabbitmq" {
  endpoint = "https://xxxxxxxx.xxxxx.cloudamqp.com"
  username = "lxlxlxlxlx"
  password = "dxdxdxdxdxdxdxdxdxd"
}

# Create a virtual host
resource "rabbitmq_vhost" "vhost_1" {
  name = "qa"
}
```
Error: Put "https://xxxxxxxx.xxxxx.cloudamqp.com": EOF

Also, I used cloudampq rabbitmq's endpoint. Is it compatible with this provider?

**Comment by BnMcG** [comment]
I'm seeing a similar issue running RabbitMQ on Kubernetes - the RabbitMQ logs show my changes are applied but the module errors out with an EOF error like you. Looking at the ingress logs it looks like all the responses are 2xx codes.

**Comment by cyrilgdn** [comment]
Hi @vrathore18 ,

Do you still have this issue?

I've just tested (for the first time) the cloudamq solution with the free solution and I was able to create a queue with the provider:

```hcl
provider "rabbitmq" {
  endpoint = "https://XXX.rmq.cloudamqp.com"
  username = "fake_user"
  password = "XXXXX"
}

# Create a virtual host
resource "rabbitmq_queue" "test" {
  name  = "test"
  vhost = "fake_user"
  settings {}
}
```


If you still have the problem, could you provide debug log with:
```
TF_LOG=debug terraform apply
```
(but **check if there's not sensitive data inside before pasting it**)

Thanks in advance.

**Comment by cyrilgdn** [comment]
I allow myself to close this issue. Feel free to open it back if the problem still occurs.
